unit SQL92Grammar;




{==============================================================================
SQL92Grammar
0.0.0.0
Date of Generation: 01/02/2025 17:11
Comment: Parses SQL-92 queries.
Author: Martin Harvey
Copyright: (c) Martin Harvey 2024.

This unit was generated by Coco/R for Delphi (www.tetzel.com)  Any code in
this file that you edit manually will be over-written when the file is
regenerated.
==============================================================================}

interface
uses  SysUtils,Classes,CocoBase,Trackables,CommonNodes;



const
maxT = 3;
type
  SymbolSet = array[0..maxT div setsize] of TBitSet;

  ESQL92Grammar = class(Exception);
  TSQL92Grammar = class;

  TSQL92GrammarScanner = class(TCocoRScanner)
  private
    FOwner : TSQL92Grammar;
function CharInIgnoreSet(const Ch : AnsiChar) : boolean;
  protected
    procedure NextCh; override;
  public
    constructor Create;

    procedure Get(var sym : integer); override; // Gets next symbol from source file

    property CurrentSymbol;
    property NextSymbol;
    property OnStatusUpdate;
    property Owner : TSQL92Grammar read fOwner write fOwner;
    property ScannerError;
    property SrcStream;
  end;  { TSQL92GrammarScanner }

  TSQL92Grammar = class(TCocoRGrammar)
  private
    { strictly internal variables }
    symSet : array[0..0] of SymbolSet; // symSet[0] = allSyncSyms

    function GetBuildDate : TDateTime;
    function GetVersion : AnsiString;
    function GetVersionStr : AnsiString;
    procedure SetVersion(const Value : AnsiString);
    function GetVersionInfo : AnsiString;
    function _In(var s : SymbolSet; x : integer) : boolean;
    procedure InitSymSet;

    {Production methods}
    procedure _SQL92Grammar;

  private
    FParentObject: TObject;

  protected
    
  protected
    { Protected Declarations }
    procedure Get; override;
  public
    { Public Declarations }
    constructor Create(AOwner : TComponent); override;
    destructor Destroy; override;

    function ErrorStr(const ErrorCode : integer; const Data : AnsiString) : AnsiString; override;
    procedure Execute; override;
    function GetScanner : TSQL92GrammarScanner;
    procedure Parse;

    property ErrorList;
    property ListStream;
    property SourceStream;
    property Successful;
    property BuildDate : TDateTime read GetBuildDate;
    property VersionStr : AnsiString read GetVersionStr;
    property VersionInfo : AnsiString read GetVersionInfo;

  public
    property ParentObject:TObject read FParentObject write FParentObject;

  published
    { Published Declarations }
    property AfterGet;
    property AfterParse;
    property AfterGenList;
    property BeforeGenList;
    property BeforeParse;
    property ClearSourceStream;
    property GenListWhen;
    property SourceFileName;
property Version : AnsiString read GetVersion write SetVersion;

    property OnCustomError;
    property OnError;
    property OnFailure;
    property OnStatusUpdate;
    property OnSuccess;
  end; { TSQL92Grammar }

implementation
uses  SQL92Nodes;



const

  EOFSYMB = 0;  TokDigitSym = 1;  TokLetterSym = 2;  NOSYMB = 3;  _noSym = NOSYMB;   {error token code}

{ --------------------------------------------------------------------------- }
{ Arbitrary Code from ATG file }
{ Arbitrary code }

{

Copyright © 2024 Martin Harvey <martin_c_harvey@hotmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the “Software”), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.

BNF  Grammar originally obtained from:

https://ronsavage.github.io/SQL/sql-92.bnf.html
https://github.com/ronsavage/SQL/blob/master/sql-92.bnf

}



{ --------------------------------------------------------------------------- }
{ ---- implementation for TSQL92GrammarScanner ---- }

procedure TSQL92GrammarScanner.NextCh;
{ Return global variable ch }
begin
  LastInputCh := CurrInputCh;
  BufferPosition := BufferPosition + 1;
  CurrInputCh := CurrentCh(BufferPosition);
  if (CurrInputCh = _EL) OR ((CurrInputCh = _LF) AND (LastInputCh <> _EL)) then
  begin
    CurrLine := CurrLine + 1;
    if Assigned(OnStatusUpdate) then
      OnStatusUpdate(Owner, cstLineNum, '', CurrLine);
    StartOfLine := BufferPosition;
  end
end;  {NextCh}


function TSQL92GrammarScanner.CharInIgnoreSet(const Ch : AnsiChar) : boolean;
begin
Result := (Ch = ' ');
end; {CharInIgnoreSet}


procedure TSQL92GrammarScanner.Get(var sym : integer);
var
  state : integer;
  label __start_get;
 begin   {Get}
__start_get:
if NumEOLInComment > 0 then
begin
  BufferPosition := BufferPosition - 1;
  NumEOLInComment := NumEOLInComment - 1;
  CurrInputCh := _CR;
end;
while CharInIgnoreSet(CurrInputCh) do
  NextCh;

  LastSymbol.Assign(CurrentSymbol);
  CurrentSymbol.Assign(NextSymbol);

  NextSymbol.Pos := BufferPosition;
  NextSymbol.Col := BufferPosition - StartOfLine;
  NextSymbol.Line := CurrLine;
  NextSymbol.Len := 0;

  ContextLen := 0;
  state := StartState[ORD(CurrInputCh)];
  bpCurrToken := BufferPosition;
  while true do
  begin
    NextCh;
    NextSymbol.Len := NextSymbol.Len + 1;
    if BufferPosition > SrcStream.Size then
    begin
      sym := EOFSYMB;
      CurrInputCh := _EF;
      BufferPosition := BufferPosition - 1;
      exit
    end;
    case state of
   1: begin
sym := TokDigitSym;
exit;
end;
   2: begin
sym := TokLetterSym;
exit;
end;
   3: begin
sym := EOFSYMB;
CurrInputCh := chNull;
BufferPosition := BufferPosition - 1;
exit
end;
    else
      begin
        sym := _noSym;
        EXIT;          // NextCh already done
      end;
    end;
  end;
end;  {Get}

constructor TSQL92GrammarScanner.Create;
begin
  inherited;
CurrentCh := CapChAt;
fStartState[  0] :=  3; fStartState[  1] :=  4; fStartState[  2] :=  4; fStartState[  3] :=  4; 
fStartState[  4] :=  4; fStartState[  5] :=  4; fStartState[  6] :=  4; fStartState[  7] :=  4; 
fStartState[  8] :=  4; fStartState[  9] :=  4; fStartState[ 10] :=  4; fStartState[ 11] :=  4; 
fStartState[ 12] :=  4; fStartState[ 13] :=  4; fStartState[ 14] :=  4; fStartState[ 15] :=  4; 
fStartState[ 16] :=  4; fStartState[ 17] :=  4; fStartState[ 18] :=  4; fStartState[ 19] :=  4; 
fStartState[ 20] :=  4; fStartState[ 21] :=  4; fStartState[ 22] :=  4; fStartState[ 23] :=  4; 
fStartState[ 24] :=  4; fStartState[ 25] :=  4; fStartState[ 26] :=  4; fStartState[ 27] :=  4; 
fStartState[ 28] :=  4; fStartState[ 29] :=  4; fStartState[ 30] :=  4; fStartState[ 31] :=  4; 
fStartState[ 32] :=  4; fStartState[ 33] :=  4; fStartState[ 34] :=  4; fStartState[ 35] :=  4; 
fStartState[ 36] :=  4; fStartState[ 37] :=  4; fStartState[ 38] :=  4; fStartState[ 39] :=  4; 
fStartState[ 40] :=  4; fStartState[ 41] :=  4; fStartState[ 42] :=  4; fStartState[ 43] :=  4; 
fStartState[ 44] :=  4; fStartState[ 45] :=  4; fStartState[ 46] :=  4; fStartState[ 47] :=  4; 
fStartState[ 48] :=  1; fStartState[ 49] :=  1; fStartState[ 50] :=  1; fStartState[ 51] :=  1; 
fStartState[ 52] :=  1; fStartState[ 53] :=  1; fStartState[ 54] :=  1; fStartState[ 55] :=  1; 
fStartState[ 56] :=  1; fStartState[ 57] :=  1; fStartState[ 58] :=  4; fStartState[ 59] :=  4; 
fStartState[ 60] :=  4; fStartState[ 61] :=  4; fStartState[ 62] :=  4; fStartState[ 63] :=  4; 
fStartState[ 64] :=  4; fStartState[ 65] :=  2; fStartState[ 66] :=  2; fStartState[ 67] :=  2; 
fStartState[ 68] :=  2; fStartState[ 69] :=  2; fStartState[ 70] :=  2; fStartState[ 71] :=  2; 
fStartState[ 72] :=  2; fStartState[ 73] :=  2; fStartState[ 74] :=  2; fStartState[ 75] :=  2; 
fStartState[ 76] :=  2; fStartState[ 77] :=  2; fStartState[ 78] :=  2; fStartState[ 79] :=  2; 
fStartState[ 80] :=  2; fStartState[ 81] :=  2; fStartState[ 82] :=  2; fStartState[ 83] :=  2; 
fStartState[ 84] :=  2; fStartState[ 85] :=  2; fStartState[ 86] :=  2; fStartState[ 87] :=  2; 
fStartState[ 88] :=  2; fStartState[ 89] :=  2; fStartState[ 90] :=  2; fStartState[ 91] :=  4; 
fStartState[ 92] :=  4; fStartState[ 93] :=  4; fStartState[ 94] :=  4; fStartState[ 95] :=  4; 
fStartState[ 96] :=  4; fStartState[ 97] :=  4; fStartState[ 98] :=  4; fStartState[ 99] :=  4; 
fStartState[100] :=  4; fStartState[101] :=  4; fStartState[102] :=  4; fStartState[103] :=  4; 
fStartState[104] :=  4; fStartState[105] :=  4; fStartState[106] :=  4; fStartState[107] :=  4; 
fStartState[108] :=  4; fStartState[109] :=  4; fStartState[110] :=  4; fStartState[111] :=  4; 
fStartState[112] :=  4; fStartState[113] :=  4; fStartState[114] :=  4; fStartState[115] :=  4; 
fStartState[116] :=  4; fStartState[117] :=  4; fStartState[118] :=  4; fStartState[119] :=  4; 
fStartState[120] :=  4; fStartState[121] :=  4; fStartState[122] :=  4; fStartState[123] :=  4; 
fStartState[124] :=  4; fStartState[125] :=  4; fStartState[126] :=  4; fStartState[127] :=  4; 
fStartState[128] :=  4; fStartState[129] :=  4; fStartState[130] :=  4; fStartState[131] :=  4; 
fStartState[132] :=  4; fStartState[133] :=  4; fStartState[134] :=  4; fStartState[135] :=  4; 
fStartState[136] :=  4; fStartState[137] :=  4; fStartState[138] :=  4; fStartState[139] :=  4; 
fStartState[140] :=  4; fStartState[141] :=  4; fStartState[142] :=  4; fStartState[143] :=  4; 
fStartState[144] :=  4; fStartState[145] :=  4; fStartState[146] :=  4; fStartState[147] :=  4; 
fStartState[148] :=  4; fStartState[149] :=  4; fStartState[150] :=  4; fStartState[151] :=  4; 
fStartState[152] :=  4; fStartState[153] :=  4; fStartState[154] :=  4; fStartState[155] :=  4; 
fStartState[156] :=  4; fStartState[157] :=  4; fStartState[158] :=  4; fStartState[159] :=  4; 
fStartState[160] :=  4; fStartState[161] :=  4; fStartState[162] :=  4; fStartState[163] :=  4; 
fStartState[164] :=  4; fStartState[165] :=  4; fStartState[166] :=  4; fStartState[167] :=  4; 
fStartState[168] :=  4; fStartState[169] :=  4; fStartState[170] :=  4; fStartState[171] :=  4; 
fStartState[172] :=  4; fStartState[173] :=  4; fStartState[174] :=  4; fStartState[175] :=  4; 
fStartState[176] :=  4; fStartState[177] :=  4; fStartState[178] :=  4; fStartState[179] :=  4; 
fStartState[180] :=  4; fStartState[181] :=  4; fStartState[182] :=  4; fStartState[183] :=  4; 
fStartState[184] :=  4; fStartState[185] :=  4; fStartState[186] :=  4; fStartState[187] :=  4; 
fStartState[188] :=  4; fStartState[189] :=  4; fStartState[190] :=  4; fStartState[191] :=  4; 
fStartState[192] :=  4; fStartState[193] :=  4; fStartState[194] :=  4; fStartState[195] :=  4; 
fStartState[196] :=  4; fStartState[197] :=  4; fStartState[198] :=  4; fStartState[199] :=  4; 
fStartState[200] :=  4; fStartState[201] :=  4; fStartState[202] :=  4; fStartState[203] :=  4; 
fStartState[204] :=  4; fStartState[205] :=  4; fStartState[206] :=  4; fStartState[207] :=  4; 
fStartState[208] :=  4; fStartState[209] :=  4; fStartState[210] :=  4; fStartState[211] :=  4; 
fStartState[212] :=  4; fStartState[213] :=  4; fStartState[214] :=  4; fStartState[215] :=  4; 
fStartState[216] :=  4; fStartState[217] :=  4; fStartState[218] :=  4; fStartState[219] :=  4; 
fStartState[220] :=  4; fStartState[221] :=  4; fStartState[222] :=  4; fStartState[223] :=  4; 
fStartState[224] :=  4; fStartState[225] :=  4; fStartState[226] :=  4; fStartState[227] :=  4; 
fStartState[228] :=  4; fStartState[229] :=  4; fStartState[230] :=  4; fStartState[231] :=  4; 
fStartState[232] :=  4; fStartState[233] :=  4; fStartState[234] :=  4; fStartState[235] :=  4; 
fStartState[236] :=  4; fStartState[237] :=  4; fStartState[238] :=  4; fStartState[239] :=  4; 
fStartState[240] :=  4; fStartState[241] :=  4; fStartState[242] :=  4; fStartState[243] :=  4; 
fStartState[244] :=  4; fStartState[245] :=  4; fStartState[246] :=  4; fStartState[247] :=  4; 
fStartState[248] :=  4; fStartState[249] :=  4; fStartState[250] :=  4; fStartState[251] :=  4; 
fStartState[252] :=  4; fStartState[253] :=  4; fStartState[254] :=  4; fStartState[255] :=  4; 
end; {Create}


{ --------------------------------------------------------------------------- }
{ ---- implementation for TSQL92Grammar ---- }

constructor TSQL92Grammar.Create(AOwner : TComponent);
begin
  inherited;
  Scanner := TSQL92GrammarScanner.Create;
  GetScanner.Owner := self;
FParseTracker := TTracker.Create;
    FLangStr := 'HTML';

  InitSymSet;
end; {Create}

destructor TSQL92Grammar.Destroy;
begin
  Scanner.Free;
FParseTracker.Free;

  inherited;
end; {Destroy}

function TSQL92Grammar.ErrorStr(const ErrorCode : integer; const Data : AnsiString) : AnsiString;
begin
  case ErrorCode of
       0 : Result := 'EOF expected';
   1 : Result := 'TokDigit expected';
   2 : Result := 'TokLetter expected';
   3 : Result := 'not expected';


  else
    if Assigned(OnCustomError) then
      Result := OnCustomError(Self, ErrorCode, Data)
    else
    begin
      Result := AnsiString('Error: ' + AnsiString(IntToStr(ErrorCode)));
      if Trim(Data) > '' then
        Result := Result + ' (' + Data + ')';
    end;
  end;  {case nr}
end; {ErrorStr}

procedure TSQL92Grammar.Execute;
begin
  ClearErrors;
  ListStream.Clear;
  Extra := 1;
  StreamPartRead := -1;

  { if there is a file name then load the file }
  if Trim(SourceFileName) <> '' then
  begin
    GetScanner.SrcStream.Clear;
    GetScanner.SrcStream.LoadFromFile(SourceFileName);
  end;

  { install error reporting procedure }
  GetScanner.ScannerError := StoreError;

  { instigate the compilation }
  DoBeforeParse;
  Parse;
  DoAfterParse;

  { generate the source listing to the ListStream }
  if (GenListWhen = glAlways) OR ((GenListWhen = glOnError) AND (ErrorList.Count > 0)) then
    GenerateListing;
  if ClearSourceStream then
    GetScanner.SrcStream.Clear;
  ListStream.Position := 0;  // goto the beginning of the stream
  if Successful AND Assigned(OnSuccess) then
    OnSuccess(Self);
  if (NOT Successful) AND Assigned(OnFailure) then
    OnFailure(Self, ErrorList.Count);
end;  {Execute}

procedure TSQL92Grammar.Get;
begin
  repeat


    GetScanner.Get(fCurrentInputSymbol);
    if fCurrentInputSymbol <= maxT then
      errDist := errDist + 1
    else
    begin
    end;
  until fCurrentInputSymbol <= maxT;
  if Assigned(AfterGet) then
    AfterGet(Self, fCurrentInputSymbol);
end;  {Get}

function TSQL92Grammar.GetScanner : TSQL92GrammarScanner;
begin
  Result := Scanner AS TSQL92GrammarScanner;
end; {GetScanner}

function TSQL92Grammar._In(var s : SymbolSet; x : integer) : boolean;
begin
  _In := x mod setsize in s[x div setsize];
end;  {_In}

procedure TSQL92Grammar._SQL92Grammar;begin
Expect(TokLetterSym);
Expect(TokDigitSym);
end;

function TSQL92Grammar.GetBuildDate : TDateTime;
const
  BDate = 42512;
  Hour = 22;
  Min = 50;
begin
  Result := BDate + EncodeTime(Hour, Min, 0 ,0);
end;

function TSQL92Grammar.GetVersion : AnsiString;
begin
  Result := '0.0.0.0';
end;

function TSQL92Grammar.GetVersionStr : AnsiString;
begin
  Result := '0.0.0.0';
end;

function TSQL92Grammar.GetVersionInfo : AnsiString;
begin
  Result := 'Comment: Parses SQL-92 queries.' + #13#10 +
'Author: Martin Harvey' + #13#10 +
'Copyright: (c) Martin Harvey 2024.';
end;

procedure TSQL92Grammar.SetVersion(const Value : AnsiString);
begin
  // This is a read only property. However, we want the value
  // to appear in the Object Inspector during design time.
end;

procedure TSQL92Grammar.Parse;
begin
  errDist := minErrDist;
GetScanner._Reset;
Get;
_SQL92Grammar;
end;  {Parse}

procedure TSQL92Grammar.InitSymSet;
begin
symSet[ 0, 0] := [EOFSYMB];
end; {InitSymSet}

end { SQL92Grammar }.    
